Page content/styling fixes and css cleanup
PollBuddy/PollBuddy pull request #288
Opened 2020-10-09 21:00 UTC by annieshi6

### Description of change(s), including why:

- privacy markdown reformatted
- update contact and about pages to use the new theme
- password placeholders standardized and password fields restyled bc current styling makes the difference between password placeholder and text jarring
- type="password" added to input fields where it was missing
- added another input field to accountinfo so changing password makes more sense (new password/confirm new/confirm old)
- misc css cleanup

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #277 #248 #247 #246 

### Screenshots (if frontend change) of before and after:

2020-10-15 04:25 UTC, hbh7 requested changes
Looks good! Just a few small things I'd like to see. I made comments on the relevant lines.

2020-10-15 04:25 UTC, hbh7 commented on PollBuddy-Server/frontend/src/pages/Privacy/Privacy.md
> +If you have any remaining concerns regarding Poll Buddy’s privacy policy or requests regarding your data, please contact us at privacy@pollbuddy.app.
Can you also make the email a mailto link?

2020-10-15 21:35 UTC, annieshi6 commented on PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
> +            <label htmlFor="newPasswordText">New password:</label>
hmm I'm not really sure how else to word it without literally putting "(Not required)" lol but looks like Neha's pr includes a separation between info and change password. Maybe these fields (old pw, new pw, confirm new pw) can go on a new page or only be made visible when you click change password?

2020-10-20 05:50 UTC, hbh7 commented on PollBuddy-Server/frontend/src/pages/AccountInfo/AccountInfo.js
> +            <label htmlFor="newPasswordText">New password:</label>
Yep looks like that's taken care of

2020-10-22 18:37 UTC, hbh7 approved these changes
Looks good!

2020-10-25 04:31 UTC, nbezanis approved these changes

2020-10-26 00:41 UTC, merged