Issue 256
PollBuddy/PollBuddy pull request #289
Opened 2020-10-11 20:50 UTC by aleong1

### Description of change(s), including why:

Went through all the individual CSS files and made sure they all had the same prefix: .Foldername-item and updated the corresponding js files to match

### Type of change(s)

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes 256
### Screenshots (if frontend change) of before and after:

2020-10-13 21:48 UTC, annieshi6 reviewed
For the most part, everything looks good! The only file I would suggest that you probably change back is index.css bc body and code are not classes.

Also note: most pull requests you're going to want to merge into frontend or backend, instead of directly into master but for this pr you're probably fine since it shouldn't break anything.

Open question to anyone else that looks at this pr: is there a purpose for index.css? if not, can we safely throw it out?

2020-10-13 22:18 UTC, annieshi6 submitted a review, later dismissed

2020-10-15 04:31 UTC, hbh7 requested changes
Just so things look a bit nicer, can you also swap out the `_`'s for `-`'s? 
Ex: `Footer-foot_links` -> `Footer-foot-links`

There's also a few naming consistency issues (looks like they were that way before) that would be great if you could fix up too. I've left comments in the code. 

Otherwise though looks great!

2020-10-15 04:31 UTC, hbh7 commented on PollBuddy-Server/frontend/src/pages/PollViewer/PollViewer.js
> +          <MDBContainer className="box Pollview-answers">
`Pollview` -> `PollViewer` and the ones below with capitalization too

2020-10-15 04:31 UTC, hbh7 commented on PollBuddy-Server/frontend/src/pages/Homepage/Homepage.scss
> +.Homepage-logo {
Let's stick with Homepage rather than Home

2020-10-16 05:01 UTC, annieshi6 submitted a review, later dismissed

2020-10-20 05:55 UTC, hbh7 approved these changes
Looks perfect! Nicely done

2020-10-20 05:56 UTC, hbh7 commented
Oh actually just one last thing, merge into frontend instead. I'll make the change and it'll auto dismiss the reviews but that's fine, I saw them so I'll merge anyways.

2020-10-20 05:59 UTC, merged