Update RegisterWithPollBuddy.js
PollBuddy/PollBuddy pull request #326
Opened 2020-11-10 20:34 UTC by mkhodak2

For Issue #311

### Description of change(s), including why:

Changed from just name text to first name/last name.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

Was not running locally unsure if it correctly changed.
### Closing issues:

- Closes #311

### Screenshots (if frontend change) of before and after:

2020-11-22 02:33 UTC, hbh7 requested changes
Just a couple things, I've left some comments with more details. Also, can you add a username field as well? Thanks

2020-11-22 02:33 UTC, hbh7 commented on PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js
> +            <label htmlFor="firstnameText">Name:</label>
You'll want to put the labels and inputs together I believe. Label1 Input1 Label2 Input2.

2020-11-22 02:33 UTC, hbh7 commented on PollBuddy-Server/frontend/src/pages/RegisterWithPollBuddy/RegisterWithPollBuddy.js
>                onChange={(evt) => { this.setState({username: evt.target.value}); }}/>
This onChange part is actually part of the tag. You'll want to include it for each I believe as that's how the input validation hooks in. Duplicate the onChange part for each, and adjust the relevant fields.

2020-11-22 20:31 UTC, hbh7 approved these changes
Looks good! I'll make another issue for adding validation for the name.

2020-11-23 09:06 UTC, annieshi6 approved these changes

2020-11-24 01:54 UTC, hbh7 commented
Frontend name validation issue: #307
Backend name validation issue: #308

2020-11-24 01:54 UTC, merged