Polls rework2
PollBuddy/PollBuddy pull request #450
Opened 2021-04-09 19:56 UTC by Isaac-the-Man

### Description of change(s), including why:

Reworked route `/api/polls/:id/submit`. Added a helper function `isLogedIn()` and a middleware `checkPollPublic()` to `utils.js`. Updated eslint to support emca 2018.

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Needs testing for logged in user once this is implemented in the frontend.

### Closing issues:

- Closes #413

### Screenshots (if frontend change) of before and after:

2021-04-13 22:06 UTC, hbh7 requested changes
Just a few small changes, everything else looks good!

2021-04-13 22:06 UTC, hbh7 commented on PollBuddy-Server/backend/modules/utils.js
> +    const poll = await mongoConnection.getDB().collection("polls").findOne({"_id": id});
This should probably have a filter to only return that one property for efficiency.

2021-04-13 22:06 UTC, hbh7 commented on PollBuddy-Server/backend/modules/utils.js
> +    const poll = await mongoConnection.getDB().collection("polls").findOne({"_id": id});
I think you just add `, { Public: true }` after the `{"_id": id}` but I'm not 100% certain.

2021-04-13 22:06 UTC, hbh7 commented on PollBuddy-Server/backend/routes/polls.js
> + * @throws 500 - An error occurred while writing to the database.
I know we don't have a clear defined format for this, but could you combine the two database messages into `An error occurred while communicating with the database.`? It's not really relevant to report to the frontend which database action failed, just that a database issue occurred and therefore the task failed. That would simplify using the endpoint too a bit. 

I would like to make that a standard format though. Thoughts from anyone?

2021-04-15 18:57 UTC, hbh7 approved these changes
Great! :)

2021-04-16 22:25 UTC, neha-deshpande001 approved these changes

2021-04-19 03:49 UTC, merged